trigger:
- main

resources:
- repo: self

variables:
- group: CICD

parameters:
- name: tag
  default: "$(Build.BuildId)"
- name: imageName
  default: "demo-page"

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: local-agent

    steps:
    - script: |
        echo "var=$(appVersion)"
        echo "tag=${{ parameters.tag }}"

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: ${{ parameters.imageName }}
        dockerfile: "**/Dockerfile"
        tags: ${{ parameters.tag }}
        arguments: '--build-arg VERSION=$(appVersion)'
        containerRegistry: registryConnection

    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: push
        containerRegistry: registryConnection
        repository: ${{ parameters.imageName }}
        tags: ${{ parameters.tag }}

- stage: Deploy
  displayName: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      name: local-agent
    steps:
    - task: AzureContainerApps@1
      inputs:
        azureSubscription: 'appDeployConnection'
        imageToDeploy: acrapps<ESTUDIANTE>.azurecr.io/${{ parameters.imageName }}:${{ parameters.tag }}
        containerAppName: 'app-demo-page-[ESTUDIANTE]' # NOMBRE DEL CONTAINER APP
        resourceGroup: <RG_NAME>
        acrUsername: $(acrUsername)
        acrPassword: $(acrPassword)
